### ISSUE TITLE
Soporte para versiones de MongoDB actualizadas

### ISSUE THREAD

**Issue by plusiv** [DemocraciaEnRed/consultas-digitales#19]
Debido a que la version 3.2 de Node está descontinuada y pronto no estará disponible: ¿Es esta aplicación compatible con versiones +4.0 de MongoDB?

**Comment by guillecro** [comment]
Buenas,

No tenemos planes por el momento de actualizar los algoritmos a las versiones 4.0, pero de hacerlo seguramente lo anunciaremos en los README.

Por el momento recomendamos usar cualquier imagen de mongo3.2 disponible en dockerhub o cualquier repositorio disponible.

**Comment by plusiv** [comment]
Entendido, muchas gracias por la pronta respuesta.
Procedo a cerrar
