### ISSUE TITLE
No hay manera de hacer funcionar Stylus

### ISSUE THREAD

**Issue by zerohashcrbn** [DemocraciaEnRed/consultas-digitales#6]
Hola a todxs

Soy de Colombia y estamos tratando de replicar consultas digitales en aras de estudiarlo y ver si se puede adaptar a nuestro parlamento. He seguido sus instrucciones y en principio no debería haber mayor inconveniente, sin embargo haga lo que haga, no sube solo la imagen de Mongo pero no la App por el puerto 3000: Error:'tried to require stylus'.

![image](https://user-images.githubusercontent.com/10604088/89740701-af35d100-da50-11ea-87bd-096ca37d6c7e.png)
 
He intentado de todo, he cambiado las versiones de nodejs desde la 10 hasta la 14 y npm desde la 3 hasta la 6 y el resultado es el mismo. Me podrían dar una luz? 

Gracias de antemano. 

PS: Este proyecto sigue activo?

**Comment by guillecro** [comment]
Hola! Que tal?

Si, el problema es que las mentes geniales de Stylus se ve que tienen un versionado muy extraño y un breaking release lo toman como minor version.

El problema: Actualizaron stylus de 0.54.7 a 0.54.8

![image](https://user-images.githubusercontent.com/8771166/89742842-bfab7300-da73-11ea-9e71-6042bc60f366.png)

#### Fix

En package.json hay que congelar stylus a "0.54.7", sin ningun "^" ni nada.
Con eso deberia andar. Esto nos paso ya, y nos rompio un monton de implementaciones.
Si, el producto está mostrando sus canas.

Pronto estaremos agregando el fix al codigo, es que estamos mas dedicados a trabajar sobre implementaciones de la cual se usa este repo como base.

PD: No te quedes desde las 3 hasta las 6, no es sano ( Pero que puedo decirte, yo tambien lo hago :P )

**Comment by zerohashcrbn** [comment]
Hola,

De verdad mil gracias por responder tan pronto. Ahora lo entiendo todo. Gracias por los consejos :). 

Saludos y gracias por este magnifico proyecto.

**Comment by zerohashcrbn** [comment]
Confirmo que el problema se ha resuelto. Procedo a cerrar el issue. Gracias nuevamente.

**Comment by guillecro** [comment]
Gracias a vos! Avisanos cualquier cosa, y nos gustaria saber mas acerca de tu proyecto, cualquier cosa, nos encuentras por aquí.
